export default [
  // UPPER_RIGHT_QUADRANT - UPPER_LEFT_QUADRANT
  ['MAXILLARY_RIGHT', 'MAXILLARY_LEFT'],
  // LOWER_RIGHT_QUADRANT - LOWER_LEFT_QUADRANT
  ['MANDIBULAR_RIGHT', 'MANDIBULAR_LEFT'],
];
